[phases.setup]
aptPkgs = ["postgresql-client", "libpq-dev"]

[phases.install]
cmds = [
  "python -m venv /app/.venv",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
